# Chapter 10
## Project: Multiclass Classification Of Flower Species

## 10.2 Import Classes and Functions

In [1]:
import numpy
from pandas import read_csv
from keras.models import Sequential 
from keras.layers import Dense 
from keras.wrappers.scikit_learn import KerasClassifier 
from keras.utils import np_utils 
from sklearn.model_selection import cross_val_score 
from sklearn.model_selection import KFold 
from sklearn.preprocessing import LabelEncoder 
from sklearn.pipeline import Pipeline 

Using TensorFlow backend.


## 10.3 Initialize Random Number Generator

In [2]:
# fix nrandom seed for reproducibility
seed = 7
numpy.random.seed(seed)

## 10.4 Load The Data

In [3]:
# http://archive.ics.uci.edu/ml/datasets/Iris
# load dataset
dataframe = read_csv("iris.csv", header=None)
dataset = dataframe.values
X = dataset[:, 0:4].astype(float)
Y = dataset[:, 4]

## 10.5 Encode The Output Variable

In [4]:
# encode class values are integers
# Iris-setosa, Iris-versicolor, Iris-virginica
# 1,    0,    0
# 0,    1,    0
# 0,    0,    1
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)
print(type(dummy_y))
print(dummy_y.shape)
print(dummy_y[0:5,])

<class 'numpy.ndarray'>
(150, 3)
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]]


## 10.6 Define The Neural Network Model

In [5]:
# There is a KerasClassifier class in Keras that can be used as an Estimator in scikit-learn.
# The network topology: 4 inputs -> [4 hidden nodes] -> 3 outputs
# define baseline model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(units=4, input_dim=4, init='normal', activation='relu'))
    model.add(Dense(units=3, init='normal', activation='sigmoid'))
    # compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# We can now create our KerasClassfier for use in scikit-learn. 
# We can also pass arguments in the construction of the KerasClessifier class 
# that will be passed on to the fit () function internally used to train the neural network. 
# Here, we pass the number of epochs nbepoch as 200 and batchrsims as 5 to use 
# when training the model. 
# Debugging is also turned off when training by setting verbose to O. 
estimator = KerasClassifier(build_fn=baseline_model, nb_epoch=200, batch_size=5, verbose=0) 

## 10.7 Evaluate The Model with k-Fold Cross-Validation

In [9]:
kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X, dummy_y, cv=kfold)
print("Accuracy: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100)) 
# Accuracy: 44.00% (17.44%)
# Accuracy: 49.33% (17.44%)
# Accuracy: 48.67% (29.07%)
# The correct accuracy should be: Accuracy: 95.33% (4.27%)
# 為何跑出來的數據與 pdf 差這麼多？

/Users/dchou/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=4, input_dim=4, activation="relu", kernel_initializer="normal")`
  import sys
/Users/dchou/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=3, activation="sigmoid", kernel_initializer="normal")`
  


Accuracy: 48.67% (29.07%)
